repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: lets black
        language: system
        types: [python]
      - id: lint
        name: lint
        entry: lets lint
        language: system
        types: [python]
